module Problems where
import Helper


p001::Integer
p001 = sum $ filter divides35 [1..1000]
            where divides35 x = x `mod` 3 ==0 || x `mod` 5 == 0
                  
                  
                  
{--p002 --Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.--}
p002 :: Integer
p002 =  sum $ filter even $ takeWhile (<4000000) myfib
                  

{--The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ? --}
                  
p003::Integer
p003 = maximum $ factorise 600851475143